timezone: America/New_York
encoding: utf-8
markdown: kramdown
domain: mark-c-valderrama.github.io
collections:
  specs:
    output: true
    permalink: "/specs/:path.:output_ext"
    permalink: /specs/:path.html
  arch:
    output: true
    permalink: "/arch/:path.:output_ext"
    permalink: /arch/:path.html
defaults:
  -
    scope:
      path: ""
      type: "specs"
    values:
      layout: "abstract"
  -
    scope:
      path: ""
      type: "arch"
    values:
      layout: "abstract"
