timezone: America/New_York
encoding: utf-8
markdown: kramdown
domain: www.smarterapp.org
collections:
  specs:
    output: true
    permalink: /specs/:path.html
  manuals:
    output: true
    permalink: /manuals/:path.html
  deployment:
    output: true
    permalink: /deployment/:path.html
  arch:
    output: true
    permalink: /arch/:path.html
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "specs"
    values:
      layout: "abstract"
  -
    scope:
      path: ""
      type: "manuals"
    values:
      layout: "abstract"
  -
    scope:
      path: ""
      type: "deployment"
    values:
      layout: "abstract"
  -
    scope:
      path: ""
      type: "arch"
    values:
      layout: "abstract"